@startuml
hide circle
title UML-ConceptClasses
left to right direction

Class User{
    Fullname
    Address
    Account_number
}

Class Meteo_Service{
    Name
    Cost
    Date_time
}

Class Payment{
    Payment_method
}


User"1" --> "*"Meteo_Service: ViewingTheService

Meteo_Service"1" --> "1"Payment: StoresPaymentData

@enduml
